### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by abarre** [fasterize/fasterize-web-extension#14]
Firefox extension should be easier to build in the future because Mozilla align their API with Chrome.
See : 
- http://arewewebextensionsyet.com/
- https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/
- https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/

**Comment by abarre** [comment]
The FF add-on is released on Github :)

**Comment by stefounet** [comment]
great!!
