### ISSUE TITLE
Missing logo in chrome store

### ISSUE THREAD

**Issue by abarre** [fasterize/fasterize-web-extension#23]
The logo don't appear in the chrome store : https://chrome.google.com/webstore/detail/fasterize-status/pophpmnchlcddhhilmnopbahlaohdfig?hl=fr

**Comment by zimski** [comment]
it's fixed :)

I moved the ownership of the extension to a `Google group` called `Fasterize` and I invited you.

You should have access as an administrator and be able to manage the extension.

**Comment by abarre** [comment]
Hi @zimski,

I don't find the Google Group `Fasterize` and my credential doesn't seem to work. Do you have a link to this group ?

**Comment by abarre** [comment]
J'ai retrouvé l'invitation mais elle a expiré. Peux-tu me l'a renvoyé ?
