### ISSUE TITLE
The extension Icon is activated (green) but the site is not optimized

### ISSUE THREAD

**Issue by zimski** [fasterize/fasterize-web-extension#24]
The extension is activated (with green color ) even if the website is not optimised.

When the webpage is not optimised by fasterize:
- When the webpage is cached, the extension icon in the navigator is green.
- When the webpage is cached with HTTP2, the icon is green with a red dot

If the extension is reserved to optimised website, it should disabled ( with a gray color ) for not fasterized website

**Comment by abarre** [comment]
I removed the detection of browser cache that is buggy. This fixes this issue.
