### ISSUE TITLE
Add Button to clear DNS Cache and Flush socket pools

### ISSUE THREAD

**Issue by InsaneBobby** [fasterize/fasterize-web-extension#33]
We often use chrome tools for Clear Host Cache, Flush Sockets Pool and Delete domain security policies.
Is it possible to have this actions in our plugin ?

**Comment by abarre** [comment]
@InsaneBobby, can you let me know if this extension works https://chrome.google.com/webstore/detail/dns-flusher/nbomnjapnclaocillijpceooehonajnk?hl=fr ?
You need to enable `chrome://flags/#extensions-on-chrome-urls` before using this extension.
If it works, we will be able to copy it on Fasterize.

**Comment by InsaneBobby** [comment]
@abarre  Yes this extension work but it only open this tab => chrome://net-internals/#dns
Can you think that it could be also  made a click on 'Clear host cache' and in this tab =>chrome://net-internals/#sockets 'Close idle sockets' and 'Flush socket pools

**Comment by abarre** [comment]
Hum, this extension is inteneded to open the tab and execute the click on Clear host cache and Close idle sockets. It doesn't work ?

**Comment by InsaneBobby** [comment]
Ah, How to verify this ?

**Comment by abarre** [comment]
I did a test after changing the /etc/host but it doesn't seem to refresh the cache. I will do more tests to be sure.

> Ah, How to verify this ?
I read the source code and I can see that the extension performs button click in JS.
